beacon-id = "au.csiro.covid19beacon"
beacon-name = "CSIRO COVID-19 Serverless Beacon"
domain_name = "covid19beacon.csiro.au"
organisation-id = "CSIRO"
organisation-name = "CSIRO"
bucket-name = "covid19-vcfs-dev"
production = false
okta_domain = "dev-8520796.okta.com"
okta_client_id = "0oaatqbqOVXL5PZzp5d5"
