beacon-id = "idn.gsilab.covid19beacon"
beacon-name = "GSILAB COVID-19 Serverless Beacon"
domain_name = "covid19beacon.gsilab.idn"
organisation-id = "GSILAB"
organisation-name = "GSILAB"
bucket-name = "gsilab-pipeline-output-dev"
production = false
okta_domain = "dev-08250124.okta.com"
okta_client_id = "0oa8nol2sy93CkD625d7"
