---
Description: WAF ACL for API, required as terraform does not support WAFv2 yet.
Parameters:
  maxRequestsPerFiveMinutes:
    Type: Number
Resources:
  ApiWafAcl:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: ApiWafAcl
      Scope: CLOUDFRONT
      Description: WAF ACL for API
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: MetricForApiWafAcl
      Rules:
        - Name: Custom-IpRequestRate
          Priority: 0
          Action:
            Block: {}
          Statement:
            RateBasedStatement:
              AggregateKeyType: IP
              Limit: !Ref maxRequestsPerFiveMinutes
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForApiWafAclIpRequestRate
        - Name: AWS-AWSManagedRulesAmazonIpReputationList
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForApiWafAclAmazonIpReputationList
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
        - Name: AWS-AWSManagedRulesUnixRuleSet
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForApiWafAclUnixRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesUnixRuleSet
        - Name: AWS-AWSManagedRulesLinuxRuleSet
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForApiWafAclLinuxRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesLinuxRuleSet
        - Name: AWS-AWSManagedRulesKnownBadInputsRuleSet
          Priority: 4
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForApiWafAclKnownBadInputsRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
        - Name: AWS-AWSManagedRulesCommonRuleSet
          Priority: 5
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: MetricForApiWafAclCommonRuleSet
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
Outputs:
  ApiAclArn:
    Value: !GetAtt ApiWafAcl.Arn
